name: Hello Flow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hello World!"

      - name: Mostrar trigger
        run: |
          echo "Trigger: $GITHUB_EVENT_NAME"

      - name: Diga vale
        run: echo "Valeu - bye!"
